[package]
name = "hello-amethyst-platformer"
version = "0.1.0"
authors = ["Noah Rosenzweig <rosenzweig.noah@gmail.com>"]
edition = "2018"

[dependencies]
amethyst = "0.10.0"
ron      = "0.4.2"
serde    = { version = "1.0.89", features = ["derive"] }
